#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR="vim"
export VISUAL="vim"

export DEFAULT_USER=$(whoami)
export BROWSER=firefox

if [[ -s "/usr/local/bin/virtualenvwrapper.sh" ]]; then
  source "/usr/local/bin/virtualenvwrapper.sh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc-secrets" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc-secrets"
fi
